services:
  openldap:
    image: bitnami/openldap:latest
    container_name: myldap
    env_file:
      - ldap.env
    ports:
      - "1389:1389"
      - "1636:1636"
    networks:
      - my-network
    volumes:
      - "openldap_data:/bitnami/openldap:z"
      - "./ldifs/:/ldifs:z"
    healthcheck:
      test: ["CMD", "ldapsearch", "-x", "-H", "ldap://localhost:1389", "-b", "dc=akshaygupta,dc=click"]
      interval: 30s
      timeout: 10s
      retries: 3

  my-server1:
    image: docker.io/akshaygupta25/custom-server
    container_name: my-server1
    networks:
      - my-network
    ports:
      - "1422:22"

  my-server2:
    image: docker.io/akshaygupta25/custom-server
    container_name: my-server2
    networks:
      - my-network
    ports:
      - "1522:22"

  my-server3:
    image: docker.io/akshaygupta25/custom-server
    container_name: my-server3
    networks:
      - my-network
    ports:
      - "1622:22"

networks:
  my-network:
    driver: bridge

volumes:
  openldap_data:
    driver: local
